# Explainable AI for data-driven design of predictive studies

Interactive demonstration on three open data sets: GBSG2, ACT, and PeakVO2. Each section runs the same steps as the corresponding `demo_*.py` script: fit the random survival forest (the recommender), evaluate it, generate recommendations from the forest's attributions on the training data, and evaluate the Cox model with each recommendation once on the test set. The recommendation rules are in `recommender.py` and the shared tools in `utils.py`.

In [1]:
# Install packages if needed (see environment.yml)
# !pip install scikit-survival shap statsmodels lifelines patsy seaborn

# GBSG 2

In [ ]:
import os
import numpy as np
import pandas as pd
from sksurv.datasets import load_gbsg2
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sksurv.preprocessing import OneHotEncoder

from utils import evaluate_recommendations

from utils import (MetricEval, CalibrationPerform, get_model, as_surv, evaluation_times,
                   recommend, evaluate_recommendations)

os.makedirs('plots', exist_ok=True)
os.makedirs('results', exist_ok=True)
%matplotlib inline

/Applications/Coding/miniconda3/envs/xai-id/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

/Users/a10345/Downloads/XAI-insight-discovery/utils.py

## Generate the recommender

In [3]:
## Load the dataset and train the naive model and the recommender.
X, y = load_gbsg2()
y = as_surv(y)

grade_str = X.loc[:, "tgrade"].astype(object).values[:, np.newaxis]
grade_num = OrdinalEncoder(categories=[["I", "II", "III"]]).fit_transform(grade_str)

X_no_grade = X.drop("tgrade", axis=1)
Xt = OneHotEncoder().fit_transform(X_no_grade)
Xt.loc[:, "tgrade"] = grade_num
con_cols = ['age', 'estrec', 'progrec', 'tsize']

Xt.rename(columns={'horTh=yes': 'horTh', 'menostat=Post': 'menostat'}, inplace=True)

# The encodings above use fixed categories; the scaler is fitted on the training split only
X_train, X_test, y_train, y_test = train_test_split(Xt, y, test_size=0.20, random_state=20)
pre = ColumnTransformer([('con', StandardScaler(), con_cols)],
                        remainder='passthrough', verbose_feature_names_out=False).set_output(transform='pandas')
X_train = pre.fit_transform(X_train)
X_test = pre.transform(X_test)

ex_model = get_model('rf', 20).fit(X_train, y_train)

## Evaluate the exploratory model

In [4]:
## Evaluate the exploratory model (random survival forest), as in the DataLoch analysis
evaluator = MetricEval(times=evaluation_times(y_train))
report = evaluator.full_report(ex_model, X_train, y_train, X_test, y_test, label='rsf')
calib = CalibrationPerform(t0=1500, n_bins=5, save_folder='plots/gbsg2/')
report.update(calib.report(ex_model, X_test, y_test, label='rsf'))
calib.calib_plot([ex_model], [(X_test, y_test)], model_labels=['rsf'],
                 filename='calibration_gbsg2_rsf.pdf')
print(pd.Series(report))

model                                                                       rsf
harrell_c                                                               0.67244
harrell_ci_low                                                         0.599391
harrell_ci_high                                                        0.740881
uno_c                                                                  0.666346
uno_tau                                                                  2014.0
mean_auc                                                               0.731707
auc_by_time                   {"420.0": 0.7910668108895572, "650.0": 0.72556...
ibs                                                                    0.162287
brier_by_time                 {"420.0": 0.07610905618187117, "650.0": 0.1541...
t0                                                                         1500
kind                                                                   survival
binned_intercept                                                      -0.083321
binned_slope                                                            1.23839
binned_n_bins_eff                                                             5
binned_min_bin_n                                                             27
conventional_slope                                                     1.236874
conventional_slope_ci_low                                              0.663822
conventional_slope_ci_high                                             1.809925
conventional_slope_p                                                   0.000023
dtype: object

## Generate recommendations

In [5]:
## Generate recommendations from the training data
scaler = pre.named_transformers_['con']
cutpoints = {}   
rec, info = recommend(ex_model, X_train, y_train, continuous=con_cols + ['pnodes'],
                      ordinal=['tgrade'], cutpoints=cutpoints, tag='gbsg2')
info['tests'].to_csv('results/gbsg2_interaction_tests.csv', index=False)
info['target'].to_csv('results/gbsg2_target_model_tests.csv', index=False)
pd.Series(info['summary']).to_csv('results/gbsg2_summary.csv')

[margin] eps=0.05: low=14, high=18
[margin] eps=0.1: low=19, high=30
[margin] eps=0.2: low=54, high=66
[margin] eps=0.3: low=82, high=96
[margin] eps=0.5: low=126, high=148
[margin/low] SHAP for 126 new patients
[margin/high] SHAP for 148 new patients
[exclusion] threshold=0.003009; 0/8 excluded
[exclusion] threshold=0.004564; 0/8 excluded
[non-linearity] 4/6 flagged: ['age', 'estrec', 'progrec', 'pnodes']
[non-linearity] 6/6 flagged: ['age', 'estrec', 'progrec', 'tsize', 'pnodes', 'tgrade']
  [age] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [estrec] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [progrec] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [tsize] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [horTh] 1 binary, 0 nominal (contrast), 6 continuous/ordinal partners
  [pnodes] 2 binary, 0 nominal (contrast), 5 continuous/ordinal partners
[interaction/low] 8 variables: 0 constant, 2 Pattern B (no clear within-value dispersion), 6 A/C; 6 screened
  [age] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [estrec] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [progrec] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [tsize] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [horTh] 1 binary, 0 nominal (contrast), 6 continuous/ordinal partners
  [pnodes] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
[interaction/high] 8 variables: 0 constant, 2 Pattern B (no clear within-value dispersion), 6 A/C; 6 screened
[interaction] 64 tests over 22 unique pairs; 2 pairs selected (unique-pair BH) by subcohort {'high': 2}, by method {'product-term regression': 2}, in both subcohorts 0
[target model] 2 screened pairs tested with spline main effects; 0 remain after BH
[margin] recommendations: exclusion=0, nonlinear=6, interaction=0 (before parameter budget)
[margin] eps=1: low=246, high=296
[margin/low] SHAP for 120 new patients

/Users/a10345/Downloads/XAI-insight-discovery/recommender.py:817: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  t['target_confirmed'] = t['target_confirmed'].fillna(False).astype(bool)

[margin/high] SHAP for 148 new patients
[exclusion] threshold=0.003629; 0/8 excluded
[exclusion] threshold=0.004558; 0/8 excluded
[non-linearity] 6/6 flagged: ['age', 'estrec', 'progrec', 'tsize', 'pnodes', 'tgrade']
[non-linearity] 6/6 flagged: ['age', 'estrec', 'progrec', 'tsize', 'pnodes', 'tgrade']
  [age] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [estrec] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [progrec] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [tsize] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [horTh] 1 binary, 0 nominal (contrast), 6 continuous/ordinal partners
  [pnodes] 2 binary, 0 nominal (contrast), 5 continuous/ordinal partners
  [tgrade] 2 binary, 0 nominal (contrast), 5 continuous/ordinal partners
[interaction/low] 8 variables: 0 constant, 1 Pattern B (no clear within-value dispersion), 7 A/C; 7 screened
  [age] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [estrec] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [progrec] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [tsize] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
  [horTh] 1 binary, 0 nominal (contrast), 6 continuous/ordinal partners
  [pnodes] 2 binary, 0 nominal (contrast n/a), 5 continuous/ordinal partners
[interaction/high] 8 variables: 0 constant, 2 Pattern B (no clear within-value dispersion), 6 A/C; 6 screened
[interaction] 71 tests over 23 unique pairs; 4 pairs selected (unique-pair BH) by subcohort {'high': 2, 'low': 4}, by method {'product-term regression': 3, 'within-stratum contrast': 1}, in both subcohorts 2
[target model] 4 screened pairs tested with spline main effects; 0 remain after BH
[margin] recommendations: exclusion=0, nonlinear=6, interaction=0 (before parameter budget)
[margin] chosen eps=0.5; stable window found

/Users/a10345/Downloads/XAI-insight-discovery/recommender.py:817: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  t['target_confirmed'] = t['target_confirmed'].fillna(False).astype(bool)
/Users/a10345/Downloads/XAI-insight-discovery/utils.py:294: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

all: 14 columns, 0 pairs -> 0 interaction terms, 0 dropped, 5 quadratics, 2 indicator columns
[riley] n=548, events=245, LR=118.0, apparent R2_CS=0.1937, heuristic shrinkage=0.881, adjusted R2_CS=0.1707; p_max by S: 0.85->18, 0.90->11, 0.95->5
RECOMMENDATIONS: {'exclusion': [], 'nonlinear': ['age', 'estrec', 'pnodes', 'progrec', 'tgrade', 'tsize'], 'interaction': {}}
SUMMARY: {'margin': 0.5, 'margin_stable': True, 'margin_selection_rule': 'stable_recommendations', 'subcohort_low': 126, 'subcohort_high': 148, 'n_tests': 64, 'n_pairs_tested': 22, 'n_pairs_screened': 2, 'n_pairs_held': 0, 'riley_p_max': 11, 'interaction_budget': 0, 'n_pairs_entered': 0}

/Users/a10345/Downloads/XAI-insight-discovery/utils.py:294: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Integrate recommendations

In [6]:
## Integrate the recommendations and evaluate each once on the test set
evaluate_recommendations(rec, X_train, X_test, y_train, y_test, t0=1500, tag='gbsg2',
                         continuous=con_cols + ['pnodes'], save_folder='plots/gbsg2/')

exclusion: 8 columns, 0 pairs -> 0 interaction terms, 0 dropped, 0 quadratics, 0 indicator columns
nonlinear: 14 columns, 0 pairs -> 0 interaction terms, 0 dropped, 5 quadratics, 2 indicator columns
interaction: 8 columns, 0 pairs -> 0 interaction terms, 0 dropped, 0 quadratics, 0 indicator columns
all: 14 columns, 0 pairs -> 0 interaction terms, 0 dropped, 5 quadratics, 2 indicator columns
[coxnet_all_pairwise] design: 36 columns (8 main and non-linear terms, 28 interactions)
[coxnet_all_pairwise] lambda.min at step 15/50 (10-fold CV partial likelihood); non-zero: 2 main and non-linear terms, 3 interactions
[PH] 2/14 terms with p<.05; smallest p = 3.96e-02
              model  harrell_c  harrell_ci_low  harrell_ci_high  uno_c  delta_c_vs_baseline  delta_ci_low  delta_ci_high  calib_conventional_slope  n_parameters
            Cox_org     0.6667          0.5848           0.7390 0.6655                  NaN           NaN            NaN                    1.2396             8
          Cox_exclu     0.6667          0.5848           0.7390 0.6655               0.0000        0.0000         0.0000                    1.2396             8
      Cox_nonlinear     0.7011          0.6296           0.7625 0.6938               0.0344       -0.0049         0.0760                    0.9432            14
          Cox_inter     0.6667          0.5848           0.7390 0.6655               0.0000        0.0000         0.0000                    1.2396             8
            Cox_all     0.7011          0.6296           0.7625 0.6938               0.0344       -0.0049         0.0760                    0.9432            14
            cox_rcs     0.7011          0.6362           0.7631 0.6955               0.0344       -0.0127         0.0921                    0.8463            23
coxnet_all_pairwise     0.6586          0.5734           0.7313 0.6545              -0.0081       -0.0316         0.0175                    1.1571            36

,model,harrell_c,harrell_ci_low,harrell_ci_high,uno_c,uno_tau,mean_auc,auc_by_time,ibs,brier_by_time,...,n_parameters,delta_c_vs_baseline,delta_ci_low,delta_ci_high,delta_p,n_main_nonzero,n_interactions_nonzero,alpha,alpha_step,cv_folds
0,Cox_org,0.666667,0.584817,0.739021,0.665457,2014.0,0.716400,"{""420.0"": 0.7565527880829863, ""650.0"": 0.70839...",0.161331,"{""420.0"": 0.07947677353086888, ""650.0"": 0.1532...",...,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cox_exclu,0.666667,0.584817,0.739021,0.665457,2014.0,0.716400,"{""420.0"": 0.7565527880829863, ""650.0"": 0.70839...",0.161331,"{""420.0"": 0.07947677353086888, ""650.0"": 0.1532...",...,8,0.000000,0.000000,0.000000,1.000,NaN,NaN,NaN,NaN,NaN
2,Cox_nonlinear,0.701116,0.629643,0.762533,0.693806,2014.0,0.761947,"{""420.0"": 0.8041967771351974, ""650.0"": 0.74484...",0.154062,"{""420.0"": 0.08096578229814516, ""650.0"": 0.1478...",...,14,0.034450,-0.004934,0.075960,0.088,NaN,NaN,NaN,NaN,NaN
3,Cox_inter,0.666667,0.584817,0.739021,0.665457,2014.0,0.716400,"{""420.0"": 0.7565527880829863, ""650.0"": 0.70839...",0.161331,"{""420.0"": 0.07947677353086888, ""650.0"": 0.1532...",...,8,0.000000,0.000000,0.000000,1.000,NaN,NaN,NaN,NaN,NaN
4,Cox_all,0.701116,0.629643,0.762533,0.693806,2014.0,0.761947,"{""420.0"": 0.8041967771351974, ""650.0"": 0.74484...",0.154062,"{""420.0"": 0.08096578229814516, ""650.0"": 0.1478...",...,14,0.034450,-0.004934,0.075960,0.088,NaN,NaN,NaN,NaN,NaN
5,cox_rcs,0.701116,0.636226,0.763088,0.695492,2014.0,0.764700,"{""420.0"": 0.8355877413407206, ""650.0"": 0.73634...",0.157095,"{""420.0"": 0.07406239168150638, ""650.0"": 0.1513...",...,23,0.034450,-0.012728,0.092092,0.174,NaN,NaN,NaN,NaN,NaN
6,coxnet_all_pairwise,0.658584,0.573355,0.731292,0.654451,2014.0,0.706633,"{""420.0"": 0.7402132883681891, ""650.0"": 0.70061...",0.165172,"{""420.0"": 0.08363358240739698, ""650.0"": 0.1557...",...,36,-0.008083,-0.031584,0.017534,0.492,2.0,3.0,0.055269,15.0,10.0

# ACT

In [7]:
import os
import pandas as pd
from sksurv.datasets import load_aids
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler

from utils import (MetricEval, CalibrationPerform, get_model, as_surv, evaluation_times,
                   recommend, evaluate_recommendations)

os.makedirs('plots/aids', exist_ok=True)
os.makedirs('results', exist_ok=True)
%matplotlib inline

## Generate the recommender

In [8]:
## Load the dataset (AIDS Clinical Trials Group 320, endpoint AIDS or death)
X, y = load_aids()
y = as_surv(y)

cat_cols = ['hemophil', 'karnof', 'sex', 'strat2', 'tx']     # binary, and karnof (ordinal)
nom_cols = ['ivdrug', 'raceth', 'txgrp']                     # nominal, more than 2 categories
con_cols = ['age', 'cd4', 'priorzdv']
# karnof is ordinal; its levels are given in order, since sorting the strings
# would put '100' before '70'
categories = [['70', '80', '90', '100'] if c == 'karnof' else sorted(X[c].astype(str).unique())
              for c in cat_cols]
X[cat_cols + nom_cols] = X[cat_cols + nom_cols].astype(str)

# Fit the encoders and scaler on the training split only. Nominal features are
# one-hot encoded and recombined for the interaction screen through `groups`.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=20)
pre = ColumnTransformer([('cat', OrdinalEncoder(categories=categories), cat_cols),
                         ('nom', OneHotEncoder(drop='first', sparse_output=False,
                                               handle_unknown='ignore'), nom_cols),
                         ('con', StandardScaler(), con_cols)],
                        verbose_feature_names_out=False).set_output(transform='pandas')
X_train = pre.fit_transform(X_train)
X_test = pre.transform(X_test)
# levels with fewer than 5 training patients (txgrp 3 and 4 have 1 and 2) are
# merged into the reference level
rare = [c for c in X_train.columns
        if c.startswith(tuple(f'{g}_' for g in nom_cols)) and X_train[c].sum() < 5]
X_train, X_test = X_train.drop(columns=rare), X_test.drop(columns=rare)
groups = {g: [c for c in X_train.columns if c.startswith(f'{g}_')] for g in nom_cols}

ex_model = get_model('rf', 20).fit(X_train, y_train)

## Evaluate the exploratory model

In [9]:
## Evaluate the exploratory model (random survival forest), as in the DataLoch analysis
evaluator = MetricEval(times=evaluation_times(y_train))
report = evaluator.full_report(ex_model, X_train, y_train, X_test, y_test, label='rsf')
calib = CalibrationPerform(t0=320, n_bins=5, save_folder='plots/aids/')
report.update(calib.report(ex_model, X_test, y_test, label='rsf'))
calib.calib_plot([ex_model], [(X_test, y_test)], model_labels=['rsf'],
                 filename='calibration_act_rsf.pdf')
print(pd.Series(report))

model                                                                       rsf
harrell_c                                                              0.742812
harrell_ci_low                                                         0.650451
harrell_ci_high                                                        0.827873
uno_c                                                                  0.734452
uno_tau                                                                   321.0
mean_auc                                                               0.754697
auc_by_time                   {"39.75": 0.7206197974705424, "90.5": 0.751899...
ibs                                                                    0.056923
brier_by_time                 {"39.75": 0.03360424715570277, "90.5": 0.05184...
t0                                                                          320
kind                                                                   survival
binned_intercept                                                      -0.785963
binned_slope                                                            1.78993
binned_n_bins_eff                                                             5
binned_min_bin_n                                                             46
conventional_slope                                                     1.037719
conventional_slope_ci_low                                              0.557744
conventional_slope_ci_high                                             1.517694
conventional_slope_p                                                   0.000023
dtype: object

## Generate recommendations

In [10]:
## Generate recommendations from the training data
scaler = pre.named_transformers_['con']
cutpoints = {}
rec, info = recommend(ex_model, X_train, y_train, continuous=con_cols, ordinal=['karnof'],
                      cutpoints=cutpoints, groups=groups, tag='act')
info['tests'].to_csv('results/act_interaction_tests.csv', index=False)
info['target'].to_csv('results/act_target_model_tests.csv', index=False)
pd.Series(info['summary']).to_csv('results/act_summary.csv')

[margin] eps=0.05: low=10, high=11
[margin] eps=0.1: low=22, high=27
[margin] eps=0.2: low=50, high=55
[margin] eps=0.3: low=72, high=84
[margin] eps=0.5: low=120, high=133
[margin/low] SHAP for 120 new patients
[margin/high] SHAP for 133 new patients
[exclusion] threshold=0.004157; 2/11 excluded
[exclusion] threshold=0.004743; 1/11 excluded
[non-linearity] 4/4 flagged: ['age', 'cd4', 'priorzdv', 'karnof']
[non-linearity] 4/4 flagged: ['age', 'cd4', 'priorzdv', 'karnof']
  [karnof] 2 binary, 3 nominal (contrast), 3 continuous/ordinal partners
  [sex] 1 binary, 3 nominal (contrast), 4 continuous/ordinal partners
  [age] 2 binary, 3 nominal (contrast n/a), 3 continuous/ordinal partners
  [cd4] 2 binary, 3 nominal (contrast n/a), 3 continuous/ordinal partners
  [priorzdv] 2 binary, 3 nominal (contrast n/a), 3 continuous/ordinal partners
  [ivdrug] 2 binary, 2 nominal (contrast), 4 continuous/ordinal partners
  [raceth] 2 binary, 2 nominal (contrast), 4 continuous/ordinal partners
[interaction/low] 10 variables: 1 constant, 2 Pattern B (no clear within-value dispersion), 7 A/C; 7 screened
  [karnof] 3 binary, 3 nominal (contrast), 3 continuous/ordinal partners
  [sex] 2 binary, 3 nominal (contrast), 4 continuous/ordinal partners
  [strat2] 2 binary, 3 nominal (contrast), 4 continuous/ordinal partners
  [tx] 2 binary, 3 nominal (contrast), 4 continuous/ordinal partners
  [age] 3 binary, 3 nominal (contrast n/a), 3 continuous/ordinal partners
  [cd4] 3 binary, 3 nominal (contrast n/a), 3 continuous/ordinal partners
  [priorzdv] 3 binary, 3 nominal (contrast n/a), 3 continuous/ordinal partners
  [raceth] 3 binary, 2 nominal (contrast), 4 continuous/ordinal partners
  [txgrp] 3 binary, 2 nominal (contrast), 4 continuous/ordinal partners
[interaction/high] 10 variables: 0 constant, 1 Pattern B (no clear within-value dispersion), 9 A/C; 9 screened
[interaction] 95 tests over 38 unique pairs; 10 pairs selected (unique-pair BH) by subcohort {'high': 9, 'low': 4}, by method {'product-term regression': 4, 'within-stratum contrast': 6}, in both subcohorts 3
[target model] 10 screened pairs tested with spline main effects; 4 remain after BH
[margin] recommendations: exclusion=1, nonlinear=4, interaction=4 (before parameter budget)
[margin] eps=1: low=288, high=259
[margin/low] SHAP for 168 new patients

/Users/a10345/Downloads/XAI-insight-discovery/recommender.py:817: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  t['target_confirmed'] = t['target_confirmed'].fillna(False).astype(bool)

[margin/high] SHAP for 126 new patients
[exclusion] threshold=0.005122; 1/11 excluded
[exclusion] threshold=0.004949; 1/11 excluded
[non-linearity] 4/4 flagged: ['age', 'cd4', 'priorzdv', 'karnof']
[non-linearity] 4/4 flagged: ['age', 'cd4', 'priorzdv', 'karnof']
  [karnof] 3 binary, 3 nominal (contrast), 3 continuous/ordinal partners
  [sex] 2 binary, 3 nominal (contrast), 4 continuous/ordinal partners
  [tx] 2 binary, 3 nominal (contrast), 4 continuous/ordinal partners
  [age] 3 binary, 3 nominal (contrast n/a), 3 continuous/ordinal partners
  [cd4] 3 binary, 3 nominal (contrast n/a), 3 continuous/ordinal partners
  [priorzdv] 3 binary, 3 nominal (contrast n/a), 3 continuous/ordinal partners
  [ivdrug] 3 binary, 2 nominal (contrast), 4 continuous/ordinal partners
  [raceth] 3 binary, 2 nominal (contrast), 4 continuous/ordinal partners
  [txgrp] 3 binary, 2 nominal (contrast), 4 continuous/ordinal partners
[interaction/low] 10 variables: 0 constant, 1 Pattern B (no clear within-value dispersion), 9 A/C; 9 screened
  [karnof] 3 binary, 3 nominal (contrast), 3 continuous/ordinal partners
  [sex] 2 binary, 3 nominal (contrast), 4 continuous/ordinal partners
  [strat2] 2 binary, 3 nominal (contrast), 4 continuous/ordinal partners
  [tx] 2 binary, 3 nominal (contrast), 4 continuous/ordinal partners
  [age] 3 binary, 3 nominal (contrast n/a), 3 continuous/ordinal partners
  [cd4] 3 binary, 3 nominal (contrast n/a), 3 continuous/ordinal partners
  [priorzdv] 3 binary, 3 nominal (contrast n/a), 3 continuous/ordinal partners
  [ivdrug] 3 binary, 2 nominal (contrast), 4 continuous/ordinal partners
  [raceth] 3 binary, 2 nominal (contrast), 4 continuous/ordinal partners
  [txgrp] 3 binary, 2 nominal (contrast), 4 continuous/ordinal partners
[interaction/high] 10 variables: 0 constant, 0 Pattern B (no clear within-value dispersion), 10 A/C; 10 screened
[interaction] 139 tests over 44 unique pairs; 29 pairs selected (unique-pair BH) by subcohort {'high': 24, 'low': 15}, by method {'product-term regression': 14, 'within-stratum contrast': 15}, in both subcohorts 10
[target model] 29 screened pairs tested with spline main effects; 1 remain after BH
[margin] recommendations: exclusion=1, nonlinear=4, interaction=1 (before parameter budget)
[margin] chosen eps=1; NOT STABLE: using the largest available margin

/Users/a10345/Downloads/XAI-insight-discovery/recommender.py:817: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  t['target_confirmed'] = t['target_confirmed'].fillna(False).astype(bool)
/Users/a10345/Downloads/XAI-insight-discovery/utils.py:294: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

all: 18 columns, 0 pairs -> 0 interaction terms, 1 dropped, 3 quadratics, 3 indicator columns
[riley] n=920, events=66, LR=87.6, apparent R2_CS=0.0908, heuristic shrinkage=0.795, adjusted R2_CS=0.0722; p_max by S: 0.85->12, 0.90->7, 0.95->3
RECOMMENDATIONS: {'exclusion': ['hemophil'], 'nonlinear': ['age', 'cd4', 'karnof', 'priorzdv'], 'interaction': {}}
SUMMARY: {'margin': 1.0, 'margin_stable': False, 'margin_selection_rule': 'largest_available_unstable', 'subcohort_low': 288, 'subcohort_high': 259, 'n_tests': 139, 'n_pairs_tested': 44, 'n_pairs_screened': 29, 'n_pairs_held': 1, 'riley_p_max': 7, 'interaction_budget': 0, 'n_pairs_entered': 0}

/Users/a10345/Downloads/XAI-insight-discovery/utils.py:294: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Integrate recommendations

In [11]:
## Integrate the recommendations and evaluate each once on the test set
evaluate_recommendations(rec, X_train, X_test, y_train, y_test, t0=320, tag='act',
                         continuous=con_cols, groups=groups, save_folder='plots/aids/')

exclusion: 13 columns, 0 pairs -> 0 interaction terms, 1 dropped, 0 quadratics, 0 indicator columns
nonlinear: 19 columns, 0 pairs -> 0 interaction terms, 0 dropped, 3 quadratics, 3 indicator columns
interaction: 14 columns, 0 pairs -> 0 interaction terms, 0 dropped, 0 quadratics, 0 indicator columns
all: 18 columns, 0 pairs -> 0 interaction terms, 1 dropped, 3 quadratics, 3 indicator columns
[coxnet_all_pairwise] design: 98 columns (14 main and non-linear terms, 84 interactions)
[coxnet_all_pairwise] lambda.min at step 28/50 (10-fold CV partial likelihood); non-zero: 7 main and non-linear terms, 31 interactions
[PH] 0/18 terms with p<.05; smallest p = 1.90e-01
              model  harrell_c  harrell_ci_low  harrell_ci_high  uno_c  delta_c_vs_baseline  delta_ci_low  delta_ci_high  calib_conventional_slope  n_parameters
            Cox_org     0.7430          0.6552           0.8274 0.7445                  NaN           NaN            NaN                    0.6504            14
          Cox_exclu     0.7451          0.6564           0.8297 0.7470               0.0021       -0.0075         0.0135                    0.6604            13
      Cox_nonlinear     0.7482          0.6606           0.8314 0.7528               0.0052       -0.0148         0.0256                    0.6315            19
          Cox_inter     0.7430          0.6552           0.8274 0.7445               0.0000        0.0000         0.0000                    0.6504            14
            Cox_all     0.7493          0.6637           0.8321 0.7567               0.0063       -0.0199         0.0332                    0.6401            18
            cox_rcs     0.7437          0.6549           0.8281 0.7479               0.0007       -0.0187         0.0190                    0.6111            23
coxnet_all_pairwise     0.7443          0.6521           0.8358 0.7494               0.0013       -0.0401         0.0382                    0.7254            98

,model,harrell_c,harrell_ci_low,harrell_ci_high,uno_c,uno_tau,mean_auc,auc_by_time,ibs,brier_by_time,...,n_parameters,delta_c_vs_baseline,delta_ci_low,delta_ci_high,delta_p,n_main_nonzero,n_interactions_nonzero,alpha,alpha_step,cv_folds
0,Cox_org,0.742987,0.655241,0.827391,0.744544,321.0,0.722922,"{""39.75"": 0.6547297284358502, ""90.5"": 0.730720...",0.056954,"{""39.75"": 0.0340445581938262, ""90.5"": 0.052758...",...,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cox_exclu,0.745078,0.656390,0.829694,0.747023,321.0,0.728933,"{""39.75"": 0.6655804207574303, ""90.5"": 0.738136...",0.056984,"{""39.75"": 0.03403633780107383, ""90.5"": 0.05278...",...,13,0.002091,-0.007460,0.013548,0.852,NaN,NaN,NaN,NaN,NaN
2,Cox_nonlinear,0.748214,0.660572,0.831426,0.752780,321.0,0.735987,"{""39.75"": 0.6788082432597144, ""90.5"": 0.741729...",0.057411,"{""39.75"": 0.03405642148124669, ""90.5"": 0.05290...",...,19,0.005227,-0.014785,0.025642,0.620,NaN,NaN,NaN,NaN,NaN
3,Cox_inter,0.742987,0.655241,0.827391,0.744544,321.0,0.722922,"{""39.75"": 0.6547297284358502, ""90.5"": 0.730720...",0.056954,"{""39.75"": 0.0340445581938262, ""90.5"": 0.052758...",...,14,0.000000,0.000000,0.000000,1.000,NaN,NaN,NaN,NaN,NaN
4,Cox_all,0.749259,0.663686,0.832135,0.756707,321.0,0.737944,"{""39.75"": 0.6862166381757486, ""90.5"": 0.746134...",0.057417,"{""39.75"": 0.03401699368234475, ""90.5"": 0.05291...",...,18,0.006273,-0.019948,0.033171,0.682,NaN,NaN,NaN,NaN,NaN
5,cox_rcs,0.743684,0.654852,0.828115,0.747858,321.0,0.734906,"{""39.75"": 0.6828598950624, ""90.5"": 0.741399427...",0.056916,"{""39.75"": 0.034047226586921164, ""90.5"": 0.0522...",...,23,0.000697,-0.018675,0.019024,0.872,NaN,NaN,NaN,NaN,NaN
6,coxnet_all_pairwise,0.744293,0.652074,0.835835,0.749411,321.0,0.720106,"{""39.75"": 0.6510497040938538, ""90.5"": 0.717214...",0.053645,"{""39.75"": 0.030766244228472437, ""90.5"": 0.0493...",...,98,0.001307,-0.040077,0.038209,0.902,7.0,31.0,0.00423,28.0,10.0

# PeakVO2

In [12]:
import os
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sksurv.util import Surv

from utils import (MetricEval, CalibrationPerform, get_model, evaluation_times,
                   recommend, evaluate_recommendations)

os.makedirs('plots/peak', exist_ok=True)
os.makedirs('results', exist_ok=True)

## Generate the recommender

In [13]:
## Load the dataset (randomForestSRC::peakVO2; systolic heart failure)
# All-cause death, with follow-up time in years. The CSV preserves all 39
# predictors from the original R dataset; died and ttodead define the outcome.
df = pd.read_csv('data/peakvo2.csv')
y = Surv.from_arrays(event=df['died'].astype(bool), time=df['ttodead'].astype(float))
X = df.drop(columns=['died', 'ttodead']).astype(float)
con_cols = ['age', 'resting.systolic.bp', 'resting.hr', 'bmi', 'lvef.metabl',
            'peak.rer', 'peak.vo2', 'interval', 'bun', 'sodium', 'hgb',
            'glucose', 'crcl']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=20)
pre = ColumnTransformer([('con', StandardScaler(), con_cols)],
                        remainder='passthrough', verbose_feature_names_out=False).set_output(transform='pandas')
X_train = pre.fit_transform(X_train)
X_test = pre.transform(X_test)

ex_model = get_model('rf', 20).fit(X_train, y_train)

## Evaluate the exploratory model

In [14]:
## Evaluate the exploratory model (random survival forest)
t0 = 3.0  # three-year calibration horizon; ttodead is measured in years
evaluator = MetricEval(times=evaluation_times(y_train))
report = evaluator.full_report(ex_model, X_train, y_train, X_test, y_test, label='rsf')
calib = CalibrationPerform(t0=t0, n_bins=5, save_folder='plots/peak/')
report.update(calib.report(ex_model, X_test, y_test, label='rsf'))
calib.calib_plot([ex_model], [(X_test, y_test)], model_labels=['rsf'],
                 filename='calibration_peak_rsf.pdf')
print(pd.Series(report))

model                                                                       rsf
harrell_c                                                              0.683295
harrell_ci_low                                                         0.637237
harrell_ci_high                                                        0.728675
uno_c                                                                  0.669474
uno_tau                                                                     9.6
mean_auc                                                               0.702299
auc_by_time                   {"1.0458590007": 0.7002188723397588, "2.751540...
ibs                                                                    0.134202
brier_by_time                 {"1.0458590007": 0.08554132405547249, "2.75154...
t0                                                                          3.0
kind                                                                   survival
binned_intercept                                                      -0.009629
binned_slope                                                           1.016521
binned_n_bins_eff                                                             5
binned_min_bin_n                                                             89
conventional_slope                                                     0.964413
conventional_slope_ci_low                                              0.699129
conventional_slope_ci_high                                             1.229697
conventional_slope_p                                                        0.0
dtype: object

## Generate recommendations

In [ ]:
## Generate recommendations from the training data
cutpoints = {}
rec, info = recommend(ex_model, X_train, y_train, continuous=con_cols, ordinal=[],
                      cutpoints=cutpoints, tag='peak')
info['tests'].to_csv('results/peak_interaction_tests.csv', index=False)
info['target'].to_csv('results/peak_target_model_tests.csv', index=False)
pd.Series(info['summary']).to_csv('results/peak_summary.csv')

[margin] eps=0.05: low=48, high=40
[margin] eps=0.1: low=100, high=69
[margin] eps=0.2: low=194, high=170
[margin/low] SHAP for 194 new patients
[margin/high] SHAP for 170 new patients
[exclusion] threshold=0.001598; 8/39 excluded
[exclusion] threshold=0.002012; 13/39 excluded
[non-linearity] 12/13 flagged: ['age', 'resting.systolic.bp', 'resting.hr', 'bmi', 'lvef.metabl', 'peak.vo2', 'interval', 'bun', 'sodium', 'hgb', 'glucose', 'crcl']
[non-linearity] 11/13 flagged: ['age', 'resting.systolic.bp', 'lvef.metabl', 'peak.rer', 'peak.vo2', 'interval', 'bun', 'sodium', 'hgb', 'glucose', 'crcl']
  [age] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [resting.systolic.bp] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [resting.hr] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [bmi] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [lvef.metabl] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [peak.rer] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [peak.vo2] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [interval] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [bun] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [sodium] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [hgb] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [glucose] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [crcl] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [betablok] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [acei] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [angioten.II] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [anti.arrhy] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [anti.coag] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [aspirin] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [digoxin] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [nitrates] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [surgery.cabg] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [surgery.pci] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [smknow] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [q.wave.mi] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [cad] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [male] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [black] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
[interaction/low] 31 variables: 0 constant, 3 Pattern B (no clear within-value dispersion), 28 A/C; 28 screened
  [age] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [resting.systolic.bp] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [resting.hr] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [bmi] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [lvef.metabl] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [peak.rer] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [peak.vo2] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [interval] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [bun] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [sodium] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [hgb] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [glucose] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [crcl] 18 binary, 0 nominal (contrast n/a), 12 continuous/ordinal partners
  [betablok] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [acei] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [angioten.II] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [anti.arrhy] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [anti.coag] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [aspirin] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [digoxin] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [diuretic.thiazide] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [insulin] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [surgery.cabg] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [q.wave.mi] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [cad] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
  [male] 17 binary, 0 nominal (contrast), 13 continuous/ordinal partners
[interaction/high] 31 variables: 0 constant, 5 Pattern B (no clear within-value dispersion), 26 A/C; 26 screened
[interaction] 1021 tests over 431 unique pairs; 16 pairs selected (unique-pair BH) by subcohort {'high': 13, 'low': 9}, by method {'product-term regression': 3, 'within-stratum contrast': 13}, in both subcohorts 6
[target model] 16 screened pairs tested with spline main effects; 1 remain after BH
[margin] recommendations: exclusion=8, nonlinear=13, interaction=1 (before parameter budget)
[margin] eps=0.3: low=287, high=243
[margin/low] SHAP for 93 new patients

/Users/a10345/Downloads/XAI-insight-discovery/recommender.py:817: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  t['target_confirmed'] = t['target_confirmed'].fillna(False).astype(bool)

## Integrate recommendations

In [ ]:
## Integrate the recommendations and evaluate each once on the test set
evaluate_recommendations(rec, X_train, X_test, y_train, y_test, t0=t0, tag='peak',
                         continuous=con_cols, save_folder='plots/peak/')